### ISSUE TITLE
Check zswag compatibility with OpenAPI YAML

### ISSUE THREAD

**Issue by MisterGC** [Klebert-Engineering/zswag#22]
**Current State**: Currently, the zswag server doesn't check if a present OpenAPI YAML is usable because of version compatibility.

**Desired Behavior**: zswag check if a present OpenAPI YAML is usable (for example zswag could put the version that has been used to generate the OpenAPI spec directly in the YAML file) - zswag should output a message if the OpenAPI spec is not compatible.

**Comment by josephbirkner** [comment]
The zswag OpenAPI parser and the server now generate very detailed error messages when an incompatible OpenAPI feature is used. Does that cover the requirement?
